site_name: Discarpet Docs
repo_url: https://github.com/replaceitem/carpet-discarpet
edit_uri: blob/master/docs/pages
repo_name: replaceitem/carpet-discarpet
docs_dir: docs/pages
site_url: https://replaceitem.github.io/carpet-discarpet/
site_description: Discarpet documentation
site_author: replaceitem
strict: true
theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.tooltips
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 2
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
plugins:
  - search
  - macros:
      include_dir: docs/include
  - replace_markdown:
      patterns:
        - icon-optional:
            oldvalue: '{:?}'
            newvalue: ':fontawesome-solid-question:{ .icon-optional title="Optional" }'
        - section_input:
            oldvalue: '{input:}'
            newvalue: ':material-download: Input parameters'
        - section_output:
            oldvalue: '{output:}'
            newvalue: ':material-upload: Output values'
        - section_output_values:
            oldvalue: '{output values:}'
            newvalue: 'Return values'
        - section_event_inputs:
            oldvalue: '{event inputs:}'
            newvalue: ':material-download: Event inputs'
        - section_output_exceptions:
            oldvalue: '{output exceptions:}'
            newvalue: 'Uncaught exceptions [:octicons-question-16:](/how-it-works.md/#discarpet-exceptions){ .icon-help title="More info" }'
        - section_query:
            oldvalue: '{query:}'
            newvalue: ':material-format-list-bulleted-type: Queryable properties [:octicons-question-16:](/how-it-works.md/#discarpet-values){ .icon-help title="More info" }'
        - section_map:
            oldvalue: '{map:}'
            newvalue: ':material-code-braces: Map entries [:octicons-question-16:](/how-it-works.md/#discarpet-parsables){ .icon-help title="More info" }'
  - abs-to-rel
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/etTDQAVSgt
      name: Join the Discord
    - icon: simple/modrinth
      link: https://modrinth.com/mod/discarpet
      name: Download on Modrinth
    - icon: simple/github
      link: https://github.com/replaceitem/carpet-discarpet
      name: GitHub
nav:
  - Home:
    - 'index.md'
    - Getting started: 'setup.md'
    - How it works: 'how-it-works.md'
    - Changelog: 'changelog.md'

  - Example scripts:
    - Chat: 'examples/chat.md'
    - Log: 'examples/log.md'
    - Grief log: 'examples/grief-log.md'
    - Reply: 'examples/reply.md'
    - Attachments: 'examples/attachments.md'
    - Embed: 'examples/embed.md'
    - Reactions: 'examples/reactions.md'
    - Status and activity: 'examples/status-and-activity.md'
    - Message components: 'examples/message-components.md'
    - Slash commands: 'examples/slash-commands.md'
    - Context menus: 'examples/context-menus.md'
    - Modal: 'examples/modal.md'

  - Functions:
    - dc_send_message: 'functions/send-message.md'
    - dc_react: 'functions/add-reaction.md'
    - dc_react: 'functions/remove-reaction.md'
    - dc_delete: 'functions/delete.md'
    - dc_set_name: 'functions/set-name.md'
    - dc_set_channel_topic: 'functions/set-channel-topic.md'
    - dc_create_thread: 'functions/create-thread.md'
    - Value functions:
      - dc_channel_from_id: 'functions/values/channel-from-id.md'
      - dc_server_from_id: 'functions/values/server-from-id.md'
      - dc_emoji_from_id: 'functions/values/emoji-from-id.md'
      - dc_sticker_from_id: 'functions/values/sticker-from-id.md'
      - dc_role_from_id: 'functions/values/role-from-id.md'
      - dc_user_from_id: 'functions/values/user-from-id.md'
      - dc_message_from_id: 'functions/values/message-from-id.md'
      - dc_webhook_from_id: 'functions/values/webhook-from-id.md'
      - dc_webhook_from_url: 'functions/values/webhook-from-url.md'
      - dc_member_from_user: 'functions/values/member-from-user.md'
    - Bot functions:
      - dc_get_bot_user: 'functions/bot/get-bot-user.md'
      - dc_set_activity: 'functions/bot/set-activity.md'
      - dc_set_status: 'functions/bot/set-status.md'
    - User functions:
      - dc_get_display_name: 'functions/users/get-display-name.md'
      - dc_get_user_color: 'functions/users/get-user-color.md'
      - dc_set_nickname: 'functions/users/set-nickname.md'
      - dc_set_timeout: 'functions/users/set-timeout.md'
      - dc_get_timeout: 'functions/users/get-timeout.md'
    - Webhook functions:
      - dc_create_webhook: 'functions/webhooks/create-webhook.md'
      - dc_send_webhook: 'functions/webhooks/send-webhook.md'
      - dc_update_webhook: 'functions/webhooks/update-webhook.md'
    - Role functions:
      - dc_add_role: 'functions/roles/add-role.md'
      - dc_remove_role: 'functions/roles/remove-role.md'
      - dc_get_user_roles: 'functions/roles/get-user-roles.md'
    - Interaction functions:
      - dc_create_application_command: 'functions/interactions/create-application-command.md'
      - dc_get_global_application_commands: 'functions/interactions/get-global-application-commands.md'
      - dc_respond_interaction: 'functions/interactions/respond-interaction.md'

  - Events:
    - __on_system_message: 'events/system-message.md'
    - __on_discord_message: 'events/discord-message.md'
    - __on_discord_message_edit: 'events/discord-message-edit.md'
    - __on_discord_message_delete: 'events/discord-message-delete.md'
    - __on_discord_reaction: 'events/discord-reaction.md'
    - __on_discord_server_member_join: 'events/discord-server-member-join.md'
    - __on_discord_server_member_leave: 'events/discord-server-member-leave.md'
    - __on_discord_slash_command: 'events/discord-command.md'
    - __on_discord_button: 'events/discord-button.md'
    - __on_discord_select_menu: 'events/discord-select-menu.md'
    - __on_discord_message_context_menu: 'events/discord-message-context-menu.md'
    - __on_discord_user_context_menu: 'events/discord-user-context-menu.md'
    - __on_discord_modal: 'events/discord-modal.md'

  - Values:
    - Message: 'values/message.md'
    - Attachment: 'values/attachment.md'
    - Emoji: 'values/emoji.md'
    - Sticker: 'values/sticker.md'
    - Reaction: 'values/reaction.md'
    - User: 'values/user.md'
    - Webhook: 'values/webhook.md'
    - Role: 'values/role.md'
    - Server: 'values/server.md'
    - Channel: 'values/channel.md'
    - Slash command: 'values/command.md'
    - Interactions:
      - Base interaction: 'values/interactions/interaction.md'
      - Slash command interaction: 'values/interactions/command.md'
      - Button interaction: 'values/interactions/button.md'
      - Select menu interaction: 'values/interactions/select-menu.md'
      - Message context menu interaction: 'values/interactions/message-context-menu.md'
      - User context menu interaction: 'values/interactions/user-context-menu.md'
      - Modal interaction: 'values/interactions/modal.md'
    
  - Parsables:
    - Message content: 'parsables/message-content.md'
    - Attachment: 'parsables/attachment.md'
    - Timestamp: 'parsables/timestamp.md'
    - Color: 'parsables/color.md'
    - Embed: 'parsables/embed.md'
    - Thread: 'parsables/thread.md'
    - Modal: 'parsables/modal.md'
    - Webhooks:
      - Webhook profile: 'parsables/webhooks/webhook-profile.md'
      - Webhook profile updater: 'parsables/webhooks/webhook-profile-updater.md'
      - Webhook message profile: 'parsables/webhooks/webhook-message-profile.md'
    - Application commands:
      - Slash command builder: 'parsables/commands/slash-command-builder.md'
      - User context menu builder: 'parsables/commands/user-context-menu-builder.md'
      - Message context menu builder: 'parsables/commands/message-context-menu-builder.md'
    - Components:
      - Base component: 'parsables/components/component.md'
      - Button component: 'parsables/components/button.md'
      - Select menu component: 'parsables/components/select-menu.md'
      - Text input component: 'parsables/components/text-input.md'