site_name: Discarpet Docs
repo_url: https://github.com/replaceitem/carpet-discarpet
edit_uri: blob/master/docs/pages
repo_name: replaceitem/carpet-discarpet
docs_dir: docs/pages
site_url: https://replaceitem.github.io/carpet-discarpet/
site_description: Discarpet documentation
site_author: replaceitem
strict: true
theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.tooltips
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 2
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
plugins:
  - abs-to-rel
  - search
  - macros:
      include_dir: docs/include
  - replace_markdown:
      patterns:
        - param_arrow:
            oldvalue: '{->}'
            newvalue: ':material-arrow-right:{ style="opacity:40%" }'
        - param_description:
            oldvalue: '{:}'
            newvalue: '<br>:material-tilde:{ style="opacity:40%" }'
        - param_optional:
            oldvalue: '{:?}'
            newvalue: ':fontawesome-solid-question:{ title="Optional parameter" }'
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/etTDQAVSgt
      name: Join the Discord
    - icon: simple/modrinth
      link: https://modrinth.com/mod/discarpet
      name: Download on Modrinth
    - icon: simple/github
      link: https://github.com/replaceitem/carpet-discarpet
      name: GitHub
nav:
  - Home: 'index.md'
  - Getting started: 'setup.md'
  - How it works: 'how-it-works.md'

  - Functions:
    - dc_send_message: 'functions/send-message.md'
    - dc_react: 'functions/react.md'
    - dc_delete: 'functions/delete.md'
    - dc_set_name: 'functions/set-name.md'
    - dc_set_channel_topic: 'functions/set-channel-topic.md'
    - dc_create_thread: 'functions/create-thread.md'
    - Value from ID functions: 'functions/value-from-id.md'
    - Bot functions:
      - dc_get_bot_user: 'functions/bot/get-bot-user.md'
      - dc_set_activity: 'functions/bot/set-activity.md'
      - dc_set_status: 'functions/bot/set-status.md'
    - User functions:
      - dc_get_display_name: 'functions/users/get-display-name.md'
      - dc_get_user_color: 'functions/users/get-user-color.md'
      - dc_set_nickname: 'functions/users/set-nickname.md'
      - dc_timeout: 'functions/users/timeout.md'
    - Role functions:
      - dc_add_role: 'functions/roles/add-role.md'
      - dc_remove_role: 'functions/roles/remove-role.md'
      - dc_get_user_roles: 'functions/roles/get-user-roles.md'
    - Interaction functions:
      - dc_create_application_command: 'functions/interactions/create-application-command.md'
      - dc_get_global_application_commands: 'functions/interactions/get-global-application-commands.md'
      - dc_respond_interaction: 'functions/interactions/respond-interaction.md'
    - Webhook functions:
      - dc_create_webhook: 'functions/webhooks/create-webhook.md'
      - dc_send_webhook: 'functions/webhooks/send-webhook.md'
      - dc_update_webhook: 'functions/webhooks/update-webhook.md'

  - Events:
    - __on_system_message: 'events/system-message.md'
    - __on_discord_message: 'events/discord-message.md'
    - __on_discord_message_edit: 'events/discord-message-edit.md'
    - __on_discord_message_delete: 'events/discord-message-delete.md'
    - __on_discord_reaction: 'events/discord-reaction.md'
    - __on_discord_server_member_join: 'events/discord-server-member-join.md'
    - __on_discord_server_member_leave: 'events/discord-server-member-leave.md'
    - __on_discord_slash_command: 'events/discord-slash-command.md'
    - __on_discord_button: 'events/discord-button.md'
    - __on_discord_select_menu: 'events/discord-select-menu.md'
    - __on_discord_user_context_menu: 'events/discord-user-context-menu.md'
    - __on_discord_message_context_menu: 'events/discord-message-context-menu.md'
    - __on_discord_modal: 'events/discord-modal.md'

  - Values:
    - Message: 'values/message.md'
    - Channel: 'values/channel.md'
    - Server: 'values/server.md'
    - User: 'values/user.md'
    - Role: 'values/role.md'
    - Attachment: 'values/attachment.md'
    - Reaction: 'values/reaction.md'
    - Emoji: 'values/emoji.md'
    - Sticker: 'values/sticker.md'
    - Webhook: 'values/webhook.md'
    - Application commands:
      - Slash command: 'values/commands/slash-command.md'
      - Message context menu: 'values/commands/message-context-menu.md'
      - User context menu: 'values/commands/user-context-menu.md'
    - Interactions:
      - Base interaction: 'values/interactions/interaction.md'
      - Slash command interaction: 'values/interactions/slash-command-interaction.md'
      - Button interaction: 'values/interactions/button-interaction.md'
      - Select menu interaction: 'values/interactions/select-menu-interaction.md'
      - Modal interaction: 'values/interactions/modal-interaction.md'
      - Message context menu interaction: 'values/interactions/message-context-menu-interaction.md'
      - User context menu interaction: 'values/interactions/user-context-menu-interaction.md'
    
  - Parsables:
    - Message content: 'parsables/message-content.md'
    - Attachment: 'parsables/attachment.md'
    - Color: 'parsables/color.md'
    - Timestamp: 'parsables/timestamp.md'
    - Allowed mentions: 'parsables/allowed-mentions.md'
    - Thread: 'parsables/thread.md'
    - Embeds:
      - Embed: 'parsables/embeds/embed.md'
      - Embed author: 'parsables/embeds/embed-author.md'
      - Embed field: 'parsables/embeds/embed-field.md'
      - Embed footer: 'parsables/embeds/embed-footer.md'
    - Webhooks:
      - Webhook profile: 'parsables/webhooks/webhook-profile.md'
      - Webhook profile updater: 'parsables/webhooks/webhook-profile-updater.md'
      - Webhook message profile: 'parsables/webhooks/webhook-message-profile.md'
    - Commands:
      - Slash command builder: 'parsables/commands/slash-command-builder.md'
      - Slash command option: 'parsables/commands/slash-command-option.md'
      - Slash command option choice: 'parsables/commands/slash-command-option-choice.md'
      - User context menu builder: 'parsables/commands/user-context-menu-builder.md'
      - Message context menu builder: 'parsables/commands/message-context-menu-builder.md'
    - Components:
      - Base component: 'parsables/components/component.md'
      - Button: 'parsables/components/button.md'
      - Text input: 'parsables/components/text-input.md'
      - Select menu: 'parsables/components/select-menu.md'
      - Select menu option: 'parsables/components/select-menu-option.md'
      - Modal: 'parsables/components/modal.md'

  - Example scripts:
    - Chat: 'examples/chat.md'
    - Activity: 'examples/activity.md'
    - Log: 'examples/log.md'
    - Grief log: 'examples/grief-log.md'
    - Reply: 'examples/reply.md'
    - Embeds: 'examples/embeds.md'
    - Attachments: 'examples/attachments.md'
    - Reactions: 'examples/reactions.md'
    - Slash commands: 'examples/slash-commands.md'
    - Context menu: 'examples/context-menu.md'
    - Message components: 'examples/message-components.md'
    - Modal: 'examples/modal.md'
